apiVersion: v1
kind: Config
clusters:
    - name: "teko-kubernetes"
      cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3SGhjTk1qTXdOREU1TVRNeE9ERTBXaGNOTXpNd05ERTJNVE14T0RFMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RFNU1UQXlPVFF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFST1NhN215Sk9McHE1Nkh1YXdlYStVN3RwSVRTZVJ1U1RFMUd4SnFQQjkKOGthVnFkZ0k5OXVBUDZ3ZmxlRlExN0pTc0FOS3Y5UzdVSTZkdll0RFVNYU1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVFhNkpBSUlOdUQvQUw2UGI5cmRCCnBXYWQvZFV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUpjWFh0M1BqbEJGUjJrWGxIMFkvOElFd004dGtJd3MKR1UwT0oxVExQRElkQWlFQXVvaU5TbjN6T1ZiSmg0eFBiYUlUcDcvNTNFYThFTkRJekhmM05lMSt6L2M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: "https://webhost.internet-box.ch:6443"
contexts:
    - name: "engweiler-teko4@teko-kubernetes"
      context:
          cluster: "teko-kubernetes"
          namespace: "teko4"
          user: "engweiler"
users:
    - name: "engweiler"
      user:
          token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IlMyd2NqVVJjeTRqWnY3RmZOUlpHTHNUTDl0NTdaSDNabGllLXJNNWgwSk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0ZWtvNCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJlbmd3ZWlsZXItdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZW5nd2VpbGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTVhZmI2YjItYTc0MS00MjdhLTg0ZTgtOWZlYzg1MGU2OWZiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRla280OmVuZ3dlaWxlciJ9.FSCFn6kBSYBPJv5a6Pl4Y9gm3EV-1CoRwZta32iS5KwnkWdknLp-wyQt7WlZuUyvCY0JQf0TTZw6y0q2BX1AZQs69CacjpMxdaO2H06yje11txFYKX6X8PHg8YhBFTgXFt4MPxPFgpNgUV4cvVep2w_UtUxG4PZErnV0Vc_gk43dHvbJnqaPcUEjSlt28xyIEiHv3AE4R9wzctH5xb0mYbqFItvlxhl3SJU_A5PWG2x7wE4lLBjcbu9jxobh1ka3xHkQfFZy2iRPUxLqdwryptD-tzrZG2UwGU2I3aQqaqUqHbb0hCHWZihWu8loSemoVxFW7A1GAI53VdxOdQAQzw"
current-context: "engweiler-teko4@teko-kubernetes"
